---
title: "Titre à trouver"
author: "TESSIER/GRAVE/DAVID/DENOUAL/SERRE/LAPORTE/LEROUX/BRUZZO"
date: "2024-10-22"
output: html_document
---
```{r}

library(dplyr)
library(readxl)
library(lubridate)

data_chiro<-read_excel("data_chiro.xlsx") #import data chiro
data_abiot_50_22<-read.csv("abiot_1950_2022.csv", sep = ";") #import data meteo 1950 -> 2022 #pensez à mettre les sources
data_abiot_23_24<-read.csv("abiot_2023_2024.csv", sep = ";") #import data meteo 2023 -> 2024
coord_chiro<-read_excel("COORD_CAPTURE.xlsx")

```

```{r}

# CLEANING AND CREATING A CLIMATIC TABLE --------------------------------------------------
data_abiot<-rbind(data_abiot_50_22, data_abiot_23_24) #On concatène les deux tables de données ensemble

data_abiot <- data_abiot %>%
  filter(AAAAMMJJ >= 20141028) %>% #delete everything before this date
  mutate(AAAAMMJJ = ymd(AAAAMMJJ)) %>%  # Conversion en format Date
  mutate(Year = year(AAAAMMJJ)) %>%  # Extraire l'année après conversion en Date
  mutate(AAAAMMJJ = format(AAAAMMJJ, "%d-%m-%Y")) %>%  # Formater la date en 'dd-mm-YYYY'
  select(NUM_POSTE, NOM_USUEL, LAT, LON, AAAAMMJJ, RR, TM, TAMPLI, FFM, Year) %>% # finir les pipes
  # Inclure la colonne Year
  rename(date = AAAAMMJJ, rain_mm = RR, Temperature = TM, ampli_Temp = TAMPLI, wind_ms = FFM, COMMUNE = NOM_USUEL)%>% #renommer les colonnes
  mutate(julian_day = yday(date)) #mettre au format jour julien


```

Function that simulates the lunar cycle as a proxy for night-time luminosity

```{r}
#Function to compute the moonlight % for a fixed date
Lune <- function(date){
  sortie <- c() #crée un vecteur vide pour stocker les résultats (cette fonction nous permet de calculer un vecteur contenant l'intensité lumineuse de la lune pour un vecteur de dates données)
  for(i in 1:length(date)){ 
    date_num <- as.numeric(as.Date(date[i],format="%d-%m-%Y")) #on transforme la date en nombre (0=01/01/1970)
    sortie[i] <- (0.5*(cos((date_num-21)*((2*pi)/(29.530589)))+1)) #formule donnant l'intensité lumineuse de la lune à une date donnée
  }
  return(sortie)
}

data_abiot$Lune <-Lune(data_abiot$date) #Adding moonlight % to the climatic table

```

data_chiro table pre-processing : 

```{r}
data_chiro <- data_chiro %>%
  select(c(Année, Commune, Localité, Date, Espèce, Sexe, Repro, Age)) %>% #select the columns we want
  filter(Sexe == "F") %>% #on ne garde que les femelles car très peu d'indices de repro sur les mâles
  filter(Age == "AD") %>% #on ne conserve que les individus 
  mutate(Date = ymd(Date)) %>% #date en jour julien
  mutate(Year = year(Date)) %>% # Créer une nouvelle colonne 'Year' contenant uniquement l'année
  mutate(Date = format(Date, "%d-%m-%Y"))%>% #formatage de la date
  mutate(julian_day = yday(Date))%>% #Date =julian_day
  rename(LIEU_DIT = Localité, COMMUNE = Commune) #on renomme
```

