---
title: "groupe 3"
autor: "Gabriel-Marie Arnault, Giuliana Brambilla, Apolline Byrdy, Anaelle Hulbert, Manon Le Bihan, Kilian Prevost, Chloé Van der Swaelmen, Léa Vuille "
editor: visual
---

# **INTRODUCTION** (Apolline et Kilian)

à faire :

-   importation du jeu de données (lien) (A)

-   Quel article, auteur, journal, référence

-   contexte biologique

-   données et variables

-   Question de recherche

-   Quel modèle et pourquoi

-   **Configuration de l'environnement et packages**

Pour analyser nos données on configure la session en nettoyant l'espace de travail. Nous aurons aussi besoin de charger les packages suivants : *knitr*, *ggplot2*, *tinytext*, *corrplot*, *plot3D*, *DHARMa*, *rcompanion* et *lattice*.

```{r init, include=FALSE}
#Configuration de la session :
rm(list=ls()) # Nettoyage de l'environnement de travail
#Chargement des packages R :
library(knitr)
opts_chunk$set(echo = FALSE, comment = "", cache = TRUE, fig.align = "center")#(TROUVER L'UTILITE ET PEUT-ÊTRE RETIRER)
library(ggplot2) # Package pour de meilleurs visuels graphiques
library(tinytex) # Pour la sortie pdf
library(corrplot)# Calcul de matrice de corrélation
library(plot3D)# Pour les graphiques 3D
library(DHARMa)# Diagnostic du modèle
library(rcompanion)# Modèle pseudo R²
library(lattice)# Graphiques multipanneaux (A CHANGER?)
```

-   vérifier si données manquantes (K)

-   mini summary (A)

# **EXPLORATION DU JEU DE DONNEES**

## 1. Présentation du jeu de données (Léa et Giuliana)

## 2. Analyse des interactions entre les variables (Chloé et Manon)

# **ANALYSE STATISTIQUE** (Anaelle et Gabriel)

# **CONCLUSION** (Apolline et Kilian)
