---


title: "Effets du pâturage sur les prairies suédoises"
group: "Bastien, Elia, Caroline, Alexia, Marine, Lily, Julie" 
>>>>>>> 75e9da09555ae3bad45e7f54a26d7c51188f42d7

bibliography: references.bib
execute: 
  freeze: auto
output: 
  html_document:
   toc: true
   toc_float: true
---

This chapter is a simple example using R

You can import R package using the code

```{r}
library(tidyverse)
library(FactoMineR)
library(dplyr)
```


and then describe the purpose of your chapter as well as executing R command.


For example a basic summary of a dataset is given by 

```{r}
df <- read.table("pollen.csv", sep = ";" , header = TRUE)
```

and produce a graph

## Effets du pâturage sur la richesse spécifique 

# Visualisation des données 

```{r}
df<-rename(.data=df,Richesse=num.species, Traitement=treatment)
```
Les variables ont été renommées

```{r}
ggplot(data=df)+
  geom_boxplot(aes(x=Traitement, y=Richesse))+
  geom_jitter(aes(x=Traitement, y=Richesse))
```


```{r}
df %>% ggplot(aes(x=Traitement, y=Richesse)) +
  geom_boxplot(aes(x=Traitement, y=Richesse))+
  geom_jitter(aes(x=Traitement, y=Richesse)) +
  labs(x="Traitement", y="Richesse spécifique") +
  ggtitle('Influence du pâturage sur la richesse spécifique')
```


A citation @bauer2023writing
