name: website
on:
  push:
    branches:
      - master
  pull_request:
  
  
jobs:
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    container: mpetienne/mode2023:0.3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install an R packages from a drat depot
        run: |
          Rscript -e "install.packages('spDataLarge', repos = 'https://nowosad.github.io/drat/', type = 'source')"
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('factoextra', 'tinytext', 'corrplot', 'plot3D', 'DHARMa', 'rcompanion', 'lattice', 'knitr', 'ggplot2', 'ggcorrplot', 'dplyr', 'FactoMineR', 'sf', 'terra', 'spData', 'tmap', 'leaflet', 'spDataLarge', 'maps', 'gifski'))" 
      - name: Additional Python packages
        run: |
          pip install numpy 
      - name: Generate slides
        run: "quarto render"
      - name: GitHub Pages action
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site