name: website
on:
  push:
    branches:
      - master
  pull_request:
  
  
jobs:
  build:
    name: Build website with rmarkdown
    runs-on: ubuntu-latest
    container: mpetienne/mode2024:0.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('rnaturalearth','rnaturalearthdata', 'ggspatial'))" 
          Rscript -e "install.packages(c('dplyr','readxl', 'lubridate', 'ggplot2','stringr', 'tidyr', 'ade4', 'spdep', 'tripack', 'sp', 'geoR', 'R2jags'))" 
          Rscript -e "install.packages(c('factoextra', 'tinytext', 'corrplot', 'plot3D', 'DHARMa', 'rcompanion','lattice'))" 
      - name: Additional Python packages
        run: |
          pip install numpy 
      - name: Generate slides
        run: "quarto render"
      - name: GitHub Pages action
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          
          

